# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

 # Example for VirtualBox:
    config.vm.provider "virtualbox" do |vb|
      vb.name = "vagrant-ubuntu-18-04"
      vb.memory = "1024"
      vb.cpus = 2
  end  

  # Share an additional folder and file to the guest VM.   
  config.vm.synced_folder ".", "/home/vagrant_data"

  config.vm.provision "file", source: "test.txt", destination: "/home/vagrant/test.txt"

 
 
  # Disable the default share of the current code directory. Doing this
  # provides improved isolation between the vagrant box and your host
  # by making sure your Vagrantfile isn't accessable to the vagrant box.
  # If you use this you may want to enable additional shared subfolders as
  # shown above.
  # config.vm.synced_folder ".", "/vagrant", disabled: true


  
# documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    
    sudo add-apt-repository ppa:deadsnakes/ppa
    apt-get update
    apt install -y  software-properties-common \
                    libpq-dev \
                    python3.8 \
                    python3-pip
    pip3 install psycopg2-binary \
                 Django
    cat /home/vagrant/test.txt
  
  SHELL
end
